#!/bin/sh
# This file is for cron job

# This if for make sure the start cgminer when there is network problem
set -x
date
C=`pidof cgminer | wc -w`
if [ "$C" != "1" ]; then
    echo "Case C"
    killall -s 9 cgminer
    sleep 1
    /etc/init.d/cgminer restart
    exit 0;
fi

A=`cat /tmp/cm.log`
B=`cgminer-api devs | grep "^   \[Last Valid Work\]"`
echo "$B" > /tmp/cm.log
if [ "$B" != "" -a "$A" == "$B" ]; then
    echo "Case B"
    killall -s 9 cgminer
    sleep 1
    /etc/init.d/cgminer restart
    exit 0;
fi

D=`cgminer-api stats | grep "^   \[miner_count\]"`
if [ "$D" == "" ]; then
	echo "Case D"
	killall -s 9 cgminer
	sleep 1
	/etc/init.d/cgminer restart
	exit 0;
fi

